return {
    "nvim-treesitter/nvim-treesitter",
    opts = {
        ensure_installed = {
            "bash",
            "c",
            "cpp",
            "help",
            "html",
            "javascript",
            "json",
            "lua",
            "markdown",
            "markdown_inline",
            "python",
            "query",
            "tsx",
            "typescript",
            "yaml",
            "go",
            "rust",
            "sql",
            "cmake",
        },
    },
}
